/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as RestaurantDashboardRouteImport } from './routes/restaurant-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForRestaurantsRouteImport } from './routes/for-restaurants'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as RestaurantDashboardIndexRouteImport } from './routes/restaurant-dashboard.index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as RestaurantDashboardSubscriptionRouteImport } from './routes/restaurant-dashboard.subscription'
import { Route as RestaurantDashboardStatsRouteImport } from './routes/restaurant-dashboard.stats'
import { Route as RestaurantDashboardStatistiquesRouteImport } from './routes/restaurant-dashboard.statistiques'
import { Route as RestaurantDashboardReviewsRouteImport } from './routes/restaurant-dashboard.reviews'
import { Route as RestaurantDashboardProfileRouteImport } from './routes/restaurant-dashboard.profile'
import { Route as RestaurantDashboardPhotosRouteImport } from './routes/restaurant-dashboard.photos'
import { Route as RestaurantDashboardFicheRouteImport } from './routes/restaurant-dashboard.fiche'
import { Route as RestaurantDashboardAvisRouteImport } from './routes/restaurant-dashboard.avis'
import { Route as RestaurantDashboardAbonnementRouteImport } from './routes/restaurant-dashboard.abonnement'

const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantDashboardRoute = RestaurantDashboardRouteImport.update({
  id: '/restaurant-dashboard',
  path: '/restaurant-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRestaurantsRoute = ForRestaurantsRouteImport.update({
  id: '/for-restaurants',
  path: '/for-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RestaurantsRoute,
} as any)
const RestaurantDashboardIndexRoute =
  RestaurantDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRoute,
} as any)
const RestaurantDashboardSubscriptionRoute =
  RestaurantDashboardSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardStatsRoute =
  RestaurantDashboardStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardStatistiquesRoute =
  RestaurantDashboardStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardReviewsRoute =
  RestaurantDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardProfileRoute =
  RestaurantDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardPhotosRoute =
  RestaurantDashboardPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardFicheRoute =
  RestaurantDashboardFicheRouteImport.update({
    id: '/fiche',
    path: '/fiche',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardAvisRoute = RestaurantDashboardAvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => RestaurantDashboardRoute,
} as any)
const RestaurantDashboardAbonnementRoute =
  RestaurantDashboardAbonnementRouteImport.update({
    id: '/abonnement',
    path: '/abonnement',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/favorites': typeof FavoritesRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/login': typeof LoginRoute
  '/restaurant-dashboard': typeof RestaurantDashboardRouteWithChildren
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/restaurant-dashboard/abonnement': typeof RestaurantDashboardAbonnementRoute
  '/restaurant-dashboard/avis': typeof RestaurantDashboardAvisRoute
  '/restaurant-dashboard/fiche': typeof RestaurantDashboardFicheRoute
  '/restaurant-dashboard/photos': typeof RestaurantDashboardPhotosRoute
  '/restaurant-dashboard/profile': typeof RestaurantDashboardProfileRoute
  '/restaurant-dashboard/reviews': typeof RestaurantDashboardReviewsRoute
  '/restaurant-dashboard/statistiques': typeof RestaurantDashboardStatistiquesRoute
  '/restaurant-dashboard/stats': typeof RestaurantDashboardStatsRoute
  '/restaurant-dashboard/subscription': typeof RestaurantDashboardSubscriptionRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/restaurant-dashboard/': typeof RestaurantDashboardIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/favorites': typeof FavoritesRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/login': typeof LoginRoute
  '/restaurant-dashboard/abonnement': typeof RestaurantDashboardAbonnementRoute
  '/restaurant-dashboard/avis': typeof RestaurantDashboardAvisRoute
  '/restaurant-dashboard/fiche': typeof RestaurantDashboardFicheRoute
  '/restaurant-dashboard/photos': typeof RestaurantDashboardPhotosRoute
  '/restaurant-dashboard/profile': typeof RestaurantDashboardProfileRoute
  '/restaurant-dashboard/reviews': typeof RestaurantDashboardReviewsRoute
  '/restaurant-dashboard/statistiques': typeof RestaurantDashboardStatistiquesRoute
  '/restaurant-dashboard/stats': typeof RestaurantDashboardStatsRoute
  '/restaurant-dashboard/subscription': typeof RestaurantDashboardSubscriptionRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/restaurant-dashboard': typeof RestaurantDashboardIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/favorites': typeof FavoritesRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/login': typeof LoginRoute
  '/restaurant-dashboard': typeof RestaurantDashboardRouteWithChildren
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/restaurant-dashboard/abonnement': typeof RestaurantDashboardAbonnementRoute
  '/restaurant-dashboard/avis': typeof RestaurantDashboardAvisRoute
  '/restaurant-dashboard/fiche': typeof RestaurantDashboardFicheRoute
  '/restaurant-dashboard/photos': typeof RestaurantDashboardPhotosRoute
  '/restaurant-dashboard/profile': typeof RestaurantDashboardProfileRoute
  '/restaurant-dashboard/reviews': typeof RestaurantDashboardReviewsRoute
  '/restaurant-dashboard/statistiques': typeof RestaurantDashboardStatistiquesRoute
  '/restaurant-dashboard/stats': typeof RestaurantDashboardStatsRoute
  '/restaurant-dashboard/subscription': typeof RestaurantDashboardSubscriptionRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/restaurant-dashboard/': typeof RestaurantDashboardIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/favorites'
    | '/for-restaurants'
    | '/login'
    | '/restaurant-dashboard'
    | '/restaurants'
    | '/restaurant-dashboard/abonnement'
    | '/restaurant-dashboard/avis'
    | '/restaurant-dashboard/fiche'
    | '/restaurant-dashboard/photos'
    | '/restaurant-dashboard/profile'
    | '/restaurant-dashboard/reviews'
    | '/restaurant-dashboard/statistiques'
    | '/restaurant-dashboard/stats'
    | '/restaurant-dashboard/subscription'
    | '/restaurants/$id'
    | '/restaurant-dashboard/'
    | '/restaurants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/favorites'
    | '/for-restaurants'
    | '/login'
    | '/restaurant-dashboard/abonnement'
    | '/restaurant-dashboard/avis'
    | '/restaurant-dashboard/fiche'
    | '/restaurant-dashboard/photos'
    | '/restaurant-dashboard/profile'
    | '/restaurant-dashboard/reviews'
    | '/restaurant-dashboard/statistiques'
    | '/restaurant-dashboard/stats'
    | '/restaurant-dashboard/subscription'
    | '/restaurants/$id'
    | '/restaurant-dashboard'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/favorites'
    | '/for-restaurants'
    | '/login'
    | '/restaurant-dashboard'
    | '/restaurants'
    | '/restaurant-dashboard/abonnement'
    | '/restaurant-dashboard/avis'
    | '/restaurant-dashboard/fiche'
    | '/restaurant-dashboard/photos'
    | '/restaurant-dashboard/profile'
    | '/restaurant-dashboard/reviews'
    | '/restaurant-dashboard/statistiques'
    | '/restaurant-dashboard/stats'
    | '/restaurant-dashboard/subscription'
    | '/restaurants/$id'
    | '/restaurant-dashboard/'
    | '/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  FavoritesRoute: typeof FavoritesRoute
  ForRestaurantsRoute: typeof ForRestaurantsRoute
  LoginRoute: typeof LoginRoute
  RestaurantDashboardRoute: typeof RestaurantDashboardRouteWithChildren
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-dashboard': {
      id: '/restaurant-dashboard'
      path: '/restaurant-dashboard'
      fullPath: '/restaurant-dashboard'
      preLoaderRoute: typeof RestaurantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-restaurants': {
      id: '/for-restaurants'
      path: '/for-restaurants'
      fullPath: '/for-restaurants'
      preLoaderRoute: typeof ForRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/restaurant-dashboard/': {
      id: '/restaurant-dashboard/'
      path: '/'
      fullPath: '/restaurant-dashboard/'
      preLoaderRoute: typeof RestaurantDashboardIndexRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/restaurant-dashboard/subscription': {
      id: '/restaurant-dashboard/subscription'
      path: '/subscription'
      fullPath: '/restaurant-dashboard/subscription'
      preLoaderRoute: typeof RestaurantDashboardSubscriptionRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/stats': {
      id: '/restaurant-dashboard/stats'
      path: '/stats'
      fullPath: '/restaurant-dashboard/stats'
      preLoaderRoute: typeof RestaurantDashboardStatsRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/statistiques': {
      id: '/restaurant-dashboard/statistiques'
      path: '/statistiques'
      fullPath: '/restaurant-dashboard/statistiques'
      preLoaderRoute: typeof RestaurantDashboardStatistiquesRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/reviews': {
      id: '/restaurant-dashboard/reviews'
      path: '/reviews'
      fullPath: '/restaurant-dashboard/reviews'
      preLoaderRoute: typeof RestaurantDashboardReviewsRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/profile': {
      id: '/restaurant-dashboard/profile'
      path: '/profile'
      fullPath: '/restaurant-dashboard/profile'
      preLoaderRoute: typeof RestaurantDashboardProfileRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/photos': {
      id: '/restaurant-dashboard/photos'
      path: '/photos'
      fullPath: '/restaurant-dashboard/photos'
      preLoaderRoute: typeof RestaurantDashboardPhotosRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/fiche': {
      id: '/restaurant-dashboard/fiche'
      path: '/fiche'
      fullPath: '/restaurant-dashboard/fiche'
      preLoaderRoute: typeof RestaurantDashboardFicheRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/avis': {
      id: '/restaurant-dashboard/avis'
      path: '/avis'
      fullPath: '/restaurant-dashboard/avis'
      preLoaderRoute: typeof RestaurantDashboardAvisRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/abonnement': {
      id: '/restaurant-dashboard/abonnement'
      path: '/abonnement'
      fullPath: '/restaurant-dashboard/abonnement'
      preLoaderRoute: typeof RestaurantDashboardAbonnementRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
  }
}

interface RestaurantDashboardRouteChildren {
  RestaurantDashboardAbonnementRoute: typeof RestaurantDashboardAbonnementRoute
  RestaurantDashboardAvisRoute: typeof RestaurantDashboardAvisRoute
  RestaurantDashboardFicheRoute: typeof RestaurantDashboardFicheRoute
  RestaurantDashboardPhotosRoute: typeof RestaurantDashboardPhotosRoute
  RestaurantDashboardProfileRoute: typeof RestaurantDashboardProfileRoute
  RestaurantDashboardReviewsRoute: typeof RestaurantDashboardReviewsRoute
  RestaurantDashboardStatistiquesRoute: typeof RestaurantDashboardStatistiquesRoute
  RestaurantDashboardStatsRoute: typeof RestaurantDashboardStatsRoute
  RestaurantDashboardSubscriptionRoute: typeof RestaurantDashboardSubscriptionRoute
  RestaurantDashboardIndexRoute: typeof RestaurantDashboardIndexRoute
}

const RestaurantDashboardRouteChildren: RestaurantDashboardRouteChildren = {
  RestaurantDashboardAbonnementRoute: RestaurantDashboardAbonnementRoute,
  RestaurantDashboardAvisRoute: RestaurantDashboardAvisRoute,
  RestaurantDashboardFicheRoute: RestaurantDashboardFicheRoute,
  RestaurantDashboardPhotosRoute: RestaurantDashboardPhotosRoute,
  RestaurantDashboardProfileRoute: RestaurantDashboardProfileRoute,
  RestaurantDashboardReviewsRoute: RestaurantDashboardReviewsRoute,
  RestaurantDashboardStatistiquesRoute: RestaurantDashboardStatistiquesRoute,
  RestaurantDashboardStatsRoute: RestaurantDashboardStatsRoute,
  RestaurantDashboardSubscriptionRoute: RestaurantDashboardSubscriptionRoute,
  RestaurantDashboardIndexRoute: RestaurantDashboardIndexRoute,
}

const RestaurantDashboardRouteWithChildren =
  RestaurantDashboardRoute._addFileChildren(RestaurantDashboardRouteChildren)

interface RestaurantsRouteChildren {
  RestaurantsIdRoute: typeof RestaurantsIdRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsIdRoute: RestaurantsIdRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  FavoritesRoute: FavoritesRoute,
  ForRestaurantsRoute: ForRestaurantsRoute,
  LoginRoute: LoginRoute,
  RestaurantDashboardRoute: RestaurantDashboardRouteWithChildren,
  RestaurantsRoute: RestaurantsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
