/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as RestaurantDashboardRouteImport } from './routes/restaurant-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForRestaurantsRouteImport } from './routes/for-restaurants'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as RestaurantDashboardIndexRouteImport } from './routes/restaurant-dashboard.index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminRestaurantsRouteImport } from './routes/super-admin.restaurants'
import { Route as SuperAdminCompaniesRouteImport } from './routes/super-admin.companies'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as RestaurantDashboardSubscriptionRouteImport } from './routes/restaurant-dashboard.subscription'
import { Route as RestaurantDashboardStatsRouteImport } from './routes/restaurant-dashboard.stats'
import { Route as RestaurantDashboardStatistiquesRouteImport } from './routes/restaurant-dashboard.statistiques'
import { Route as RestaurantDashboardReviewsRouteImport } from './routes/restaurant-dashboard.reviews'
import { Route as RestaurantDashboardProfileRouteImport } from './routes/restaurant-dashboard.profile'
import { Route as RestaurantDashboardPhotosRouteImport } from './routes/restaurant-dashboard.photos'
import { Route as RestaurantDashboardOpeningHoursRouteImport } from './routes/restaurant-dashboard.opening-hours'
import { Route as RestaurantDashboardOffresRouteImport } from './routes/restaurant-dashboard.offres'
import { Route as RestaurantDashboardOffersRouteImport } from './routes/restaurant-dashboard.offers'
import { Route as RestaurantDashboardHorairesRouteImport } from './routes/restaurant-dashboard.horaires'
import { Route as RestaurantDashboardFicheRouteImport } from './routes/restaurant-dashboard.fiche'
import { Route as RestaurantDashboardAvisRouteImport } from './routes/restaurant-dashboard.avis'
import { Route as RestaurantDashboardAbonnementRouteImport } from './routes/restaurant-dashboard.abonnement'
import { Route as LegalMentionsLegalesRouteImport } from './routes/legal.mentions-legales'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal.confidentialite'
import { Route as LegalCgvRouteImport } from './routes/legal.cgv'
import { Route as LegalCguRouteImport } from './routes/legal.cgu'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantDashboardRoute = RestaurantDashboardRouteImport.update({
  id: '/restaurant-dashboard',
  path: '/restaurant-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRestaurantsRoute = ForRestaurantsRouteImport.update({
  id: '/for-restaurants',
  path: '/for-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RestaurantsRoute,
} as any)
const RestaurantDashboardIndexRoute =
  RestaurantDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminRestaurantsRoute = SuperAdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminCompaniesRoute = SuperAdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => SuperAdminRoute,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRoute,
} as any)
const RestaurantDashboardSubscriptionRoute =
  RestaurantDashboardSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardStatsRoute =
  RestaurantDashboardStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardStatistiquesRoute =
  RestaurantDashboardStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardReviewsRoute =
  RestaurantDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardProfileRoute =
  RestaurantDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardPhotosRoute =
  RestaurantDashboardPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardOpeningHoursRoute =
  RestaurantDashboardOpeningHoursRouteImport.update({
    id: '/opening-hours',
    path: '/opening-hours',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardOffresRoute =
  RestaurantDashboardOffresRouteImport.update({
    id: '/offres',
    path: '/offres',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardOffersRoute =
  RestaurantDashboardOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardHorairesRoute =
  RestaurantDashboardHorairesRouteImport.update({
    id: '/horaires',
    path: '/horaires',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardFicheRoute =
  RestaurantDashboardFicheRouteImport.update({
    id: '/fiche',
    path: '/fiche',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardAvisRoute = RestaurantDashboardAvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => RestaurantDashboardRoute,
} as any)
const RestaurantDashboardAbonnementRoute =
  RestaurantDashboardAbonnementRouteImport.update({
    id: '/abonnement',
    path: '/abonnement',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const LegalMentionsLegalesRoute = LegalMentionsLegalesRouteImport.update({
  id: '/legal/mentions-legales',
  path: '/legal/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/legal/confidentialite',
  path: '/legal/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCgvRoute = LegalCgvRouteImport.update({
  id: '/legal/cgv',
  path: '/legal/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/favorites': typeof FavoritesRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/login': typeof LoginRoute
  '/restaurant-dashboard': typeof RestaurantDashboardRouteWithChildren
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/restaurant-dashboard/abonnement': typeof RestaurantDashboardAbonnementRoute
  '/restaurant-dashboard/avis': typeof RestaurantDashboardAvisRoute
  '/restaurant-dashboard/fiche': typeof RestaurantDashboardFicheRoute
  '/restaurant-dashboard/horaires': typeof RestaurantDashboardHorairesRoute
  '/restaurant-dashboard/offers': typeof RestaurantDashboardOffersRoute
  '/restaurant-dashboard/offres': typeof RestaurantDashboardOffresRoute
  '/restaurant-dashboard/opening-hours': typeof RestaurantDashboardOpeningHoursRoute
  '/restaurant-dashboard/photos': typeof RestaurantDashboardPhotosRoute
  '/restaurant-dashboard/profile': typeof RestaurantDashboardProfileRoute
  '/restaurant-dashboard/reviews': typeof RestaurantDashboardReviewsRoute
  '/restaurant-dashboard/statistiques': typeof RestaurantDashboardStatistiquesRoute
  '/restaurant-dashboard/stats': typeof RestaurantDashboardStatsRoute
  '/restaurant-dashboard/subscription': typeof RestaurantDashboardSubscriptionRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/restaurants': typeof SuperAdminRestaurantsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/restaurant-dashboard/': typeof RestaurantDashboardIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/favorites': typeof FavoritesRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/restaurant-dashboard/abonnement': typeof RestaurantDashboardAbonnementRoute
  '/restaurant-dashboard/avis': typeof RestaurantDashboardAvisRoute
  '/restaurant-dashboard/fiche': typeof RestaurantDashboardFicheRoute
  '/restaurant-dashboard/horaires': typeof RestaurantDashboardHorairesRoute
  '/restaurant-dashboard/offers': typeof RestaurantDashboardOffersRoute
  '/restaurant-dashboard/offres': typeof RestaurantDashboardOffresRoute
  '/restaurant-dashboard/opening-hours': typeof RestaurantDashboardOpeningHoursRoute
  '/restaurant-dashboard/photos': typeof RestaurantDashboardPhotosRoute
  '/restaurant-dashboard/profile': typeof RestaurantDashboardProfileRoute
  '/restaurant-dashboard/reviews': typeof RestaurantDashboardReviewsRoute
  '/restaurant-dashboard/statistiques': typeof RestaurantDashboardStatistiquesRoute
  '/restaurant-dashboard/stats': typeof RestaurantDashboardStatsRoute
  '/restaurant-dashboard/subscription': typeof RestaurantDashboardSubscriptionRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/restaurants': typeof SuperAdminRestaurantsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/restaurant-dashboard': typeof RestaurantDashboardIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/favorites': typeof FavoritesRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/login': typeof LoginRoute
  '/restaurant-dashboard': typeof RestaurantDashboardRouteWithChildren
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/restaurant-dashboard/abonnement': typeof RestaurantDashboardAbonnementRoute
  '/restaurant-dashboard/avis': typeof RestaurantDashboardAvisRoute
  '/restaurant-dashboard/fiche': typeof RestaurantDashboardFicheRoute
  '/restaurant-dashboard/horaires': typeof RestaurantDashboardHorairesRoute
  '/restaurant-dashboard/offers': typeof RestaurantDashboardOffersRoute
  '/restaurant-dashboard/offres': typeof RestaurantDashboardOffresRoute
  '/restaurant-dashboard/opening-hours': typeof RestaurantDashboardOpeningHoursRoute
  '/restaurant-dashboard/photos': typeof RestaurantDashboardPhotosRoute
  '/restaurant-dashboard/profile': typeof RestaurantDashboardProfileRoute
  '/restaurant-dashboard/reviews': typeof RestaurantDashboardReviewsRoute
  '/restaurant-dashboard/statistiques': typeof RestaurantDashboardStatistiquesRoute
  '/restaurant-dashboard/stats': typeof RestaurantDashboardStatsRoute
  '/restaurant-dashboard/subscription': typeof RestaurantDashboardSubscriptionRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/restaurants': typeof SuperAdminRestaurantsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/restaurant-dashboard/': typeof RestaurantDashboardIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/favorites'
    | '/for-restaurants'
    | '/login'
    | '/restaurant-dashboard'
    | '/restaurants'
    | '/sitemap.xml'
    | '/super-admin'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/restaurant-dashboard/abonnement'
    | '/restaurant-dashboard/avis'
    | '/restaurant-dashboard/fiche'
    | '/restaurant-dashboard/horaires'
    | '/restaurant-dashboard/offers'
    | '/restaurant-dashboard/offres'
    | '/restaurant-dashboard/opening-hours'
    | '/restaurant-dashboard/photos'
    | '/restaurant-dashboard/profile'
    | '/restaurant-dashboard/reviews'
    | '/restaurant-dashboard/statistiques'
    | '/restaurant-dashboard/stats'
    | '/restaurant-dashboard/subscription'
    | '/restaurants/$id'
    | '/super-admin/companies'
    | '/super-admin/restaurants'
    | '/super-admin/users'
    | '/restaurant-dashboard/'
    | '/restaurants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/favorites'
    | '/for-restaurants'
    | '/login'
    | '/sitemap.xml'
    | '/super-admin'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/restaurant-dashboard/abonnement'
    | '/restaurant-dashboard/avis'
    | '/restaurant-dashboard/fiche'
    | '/restaurant-dashboard/horaires'
    | '/restaurant-dashboard/offers'
    | '/restaurant-dashboard/offres'
    | '/restaurant-dashboard/opening-hours'
    | '/restaurant-dashboard/photos'
    | '/restaurant-dashboard/profile'
    | '/restaurant-dashboard/reviews'
    | '/restaurant-dashboard/statistiques'
    | '/restaurant-dashboard/stats'
    | '/restaurant-dashboard/subscription'
    | '/restaurants/$id'
    | '/super-admin/companies'
    | '/super-admin/restaurants'
    | '/super-admin/users'
    | '/restaurant-dashboard'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/favorites'
    | '/for-restaurants'
    | '/login'
    | '/restaurant-dashboard'
    | '/restaurants'
    | '/sitemap.xml'
    | '/super-admin'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/restaurant-dashboard/abonnement'
    | '/restaurant-dashboard/avis'
    | '/restaurant-dashboard/fiche'
    | '/restaurant-dashboard/horaires'
    | '/restaurant-dashboard/offers'
    | '/restaurant-dashboard/offres'
    | '/restaurant-dashboard/opening-hours'
    | '/restaurant-dashboard/photos'
    | '/restaurant-dashboard/profile'
    | '/restaurant-dashboard/reviews'
    | '/restaurant-dashboard/statistiques'
    | '/restaurant-dashboard/stats'
    | '/restaurant-dashboard/subscription'
    | '/restaurants/$id'
    | '/super-admin/companies'
    | '/super-admin/restaurants'
    | '/super-admin/users'
    | '/restaurant-dashboard/'
    | '/restaurants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  FavoritesRoute: typeof FavoritesRoute
  ForRestaurantsRoute: typeof ForRestaurantsRoute
  LoginRoute: typeof LoginRoute
  RestaurantDashboardRoute: typeof RestaurantDashboardRouteWithChildren
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  LegalCguRoute: typeof LegalCguRoute
  LegalCgvRoute: typeof LegalCgvRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalMentionsLegalesRoute: typeof LegalMentionsLegalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-dashboard': {
      id: '/restaurant-dashboard'
      path: '/restaurant-dashboard'
      fullPath: '/restaurant-dashboard'
      preLoaderRoute: typeof RestaurantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-restaurants': {
      id: '/for-restaurants'
      path: '/for-restaurants'
      fullPath: '/for-restaurants'
      preLoaderRoute: typeof ForRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/restaurant-dashboard/': {
      id: '/restaurant-dashboard/'
      path: '/'
      fullPath: '/restaurant-dashboard/'
      preLoaderRoute: typeof RestaurantDashboardIndexRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/restaurants': {
      id: '/super-admin/restaurants'
      path: '/restaurants'
      fullPath: '/super-admin/restaurants'
      preLoaderRoute: typeof SuperAdminRestaurantsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/companies': {
      id: '/super-admin/companies'
      path: '/companies'
      fullPath: '/super-admin/companies'
      preLoaderRoute: typeof SuperAdminCompaniesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/restaurant-dashboard/subscription': {
      id: '/restaurant-dashboard/subscription'
      path: '/subscription'
      fullPath: '/restaurant-dashboard/subscription'
      preLoaderRoute: typeof RestaurantDashboardSubscriptionRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/stats': {
      id: '/restaurant-dashboard/stats'
      path: '/stats'
      fullPath: '/restaurant-dashboard/stats'
      preLoaderRoute: typeof RestaurantDashboardStatsRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/statistiques': {
      id: '/restaurant-dashboard/statistiques'
      path: '/statistiques'
      fullPath: '/restaurant-dashboard/statistiques'
      preLoaderRoute: typeof RestaurantDashboardStatistiquesRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/reviews': {
      id: '/restaurant-dashboard/reviews'
      path: '/reviews'
      fullPath: '/restaurant-dashboard/reviews'
      preLoaderRoute: typeof RestaurantDashboardReviewsRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/profile': {
      id: '/restaurant-dashboard/profile'
      path: '/profile'
      fullPath: '/restaurant-dashboard/profile'
      preLoaderRoute: typeof RestaurantDashboardProfileRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/photos': {
      id: '/restaurant-dashboard/photos'
      path: '/photos'
      fullPath: '/restaurant-dashboard/photos'
      preLoaderRoute: typeof RestaurantDashboardPhotosRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/opening-hours': {
      id: '/restaurant-dashboard/opening-hours'
      path: '/opening-hours'
      fullPath: '/restaurant-dashboard/opening-hours'
      preLoaderRoute: typeof RestaurantDashboardOpeningHoursRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/offres': {
      id: '/restaurant-dashboard/offres'
      path: '/offres'
      fullPath: '/restaurant-dashboard/offres'
      preLoaderRoute: typeof RestaurantDashboardOffresRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/offers': {
      id: '/restaurant-dashboard/offers'
      path: '/offers'
      fullPath: '/restaurant-dashboard/offers'
      preLoaderRoute: typeof RestaurantDashboardOffersRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/horaires': {
      id: '/restaurant-dashboard/horaires'
      path: '/horaires'
      fullPath: '/restaurant-dashboard/horaires'
      preLoaderRoute: typeof RestaurantDashboardHorairesRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/fiche': {
      id: '/restaurant-dashboard/fiche'
      path: '/fiche'
      fullPath: '/restaurant-dashboard/fiche'
      preLoaderRoute: typeof RestaurantDashboardFicheRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/avis': {
      id: '/restaurant-dashboard/avis'
      path: '/avis'
      fullPath: '/restaurant-dashboard/avis'
      preLoaderRoute: typeof RestaurantDashboardAvisRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant-dashboard/abonnement': {
      id: '/restaurant-dashboard/abonnement'
      path: '/abonnement'
      fullPath: '/restaurant-dashboard/abonnement'
      preLoaderRoute: typeof RestaurantDashboardAbonnementRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/legal/mentions-legales': {
      id: '/legal/mentions-legales'
      path: '/legal/mentions-legales'
      fullPath: '/legal/mentions-legales'
      preLoaderRoute: typeof LegalMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/legal/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgv': {
      id: '/legal/cgv'
      path: '/legal/cgv'
      fullPath: '/legal/cgv'
      preLoaderRoute: typeof LegalCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RestaurantDashboardRouteChildren {
  RestaurantDashboardAbonnementRoute: typeof RestaurantDashboardAbonnementRoute
  RestaurantDashboardAvisRoute: typeof RestaurantDashboardAvisRoute
  RestaurantDashboardFicheRoute: typeof RestaurantDashboardFicheRoute
  RestaurantDashboardHorairesRoute: typeof RestaurantDashboardHorairesRoute
  RestaurantDashboardOffersRoute: typeof RestaurantDashboardOffersRoute
  RestaurantDashboardOffresRoute: typeof RestaurantDashboardOffresRoute
  RestaurantDashboardOpeningHoursRoute: typeof RestaurantDashboardOpeningHoursRoute
  RestaurantDashboardPhotosRoute: typeof RestaurantDashboardPhotosRoute
  RestaurantDashboardProfileRoute: typeof RestaurantDashboardProfileRoute
  RestaurantDashboardReviewsRoute: typeof RestaurantDashboardReviewsRoute
  RestaurantDashboardStatistiquesRoute: typeof RestaurantDashboardStatistiquesRoute
  RestaurantDashboardStatsRoute: typeof RestaurantDashboardStatsRoute
  RestaurantDashboardSubscriptionRoute: typeof RestaurantDashboardSubscriptionRoute
  RestaurantDashboardIndexRoute: typeof RestaurantDashboardIndexRoute
}

const RestaurantDashboardRouteChildren: RestaurantDashboardRouteChildren = {
  RestaurantDashboardAbonnementRoute: RestaurantDashboardAbonnementRoute,
  RestaurantDashboardAvisRoute: RestaurantDashboardAvisRoute,
  RestaurantDashboardFicheRoute: RestaurantDashboardFicheRoute,
  RestaurantDashboardHorairesRoute: RestaurantDashboardHorairesRoute,
  RestaurantDashboardOffersRoute: RestaurantDashboardOffersRoute,
  RestaurantDashboardOffresRoute: RestaurantDashboardOffresRoute,
  RestaurantDashboardOpeningHoursRoute: RestaurantDashboardOpeningHoursRoute,
  RestaurantDashboardPhotosRoute: RestaurantDashboardPhotosRoute,
  RestaurantDashboardProfileRoute: RestaurantDashboardProfileRoute,
  RestaurantDashboardReviewsRoute: RestaurantDashboardReviewsRoute,
  RestaurantDashboardStatistiquesRoute: RestaurantDashboardStatistiquesRoute,
  RestaurantDashboardStatsRoute: RestaurantDashboardStatsRoute,
  RestaurantDashboardSubscriptionRoute: RestaurantDashboardSubscriptionRoute,
  RestaurantDashboardIndexRoute: RestaurantDashboardIndexRoute,
}

const RestaurantDashboardRouteWithChildren =
  RestaurantDashboardRoute._addFileChildren(RestaurantDashboardRouteChildren)

interface RestaurantsRouteChildren {
  RestaurantsIdRoute: typeof RestaurantsIdRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsIdRoute: RestaurantsIdRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminCompaniesRoute: typeof SuperAdminCompaniesRoute
  SuperAdminRestaurantsRoute: typeof SuperAdminRestaurantsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminCompaniesRoute: SuperAdminCompaniesRoute,
  SuperAdminRestaurantsRoute: SuperAdminRestaurantsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  FavoritesRoute: FavoritesRoute,
  ForRestaurantsRoute: ForRestaurantsRoute,
  LoginRoute: LoginRoute,
  RestaurantDashboardRoute: RestaurantDashboardRouteWithChildren,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  LegalCguRoute: LegalCguRoute,
  LegalCgvRoute: LegalCgvRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalMentionsLegalesRoute: LegalMentionsLegalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
